name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    strategy:
      matrix:
        node-version: ['8', '10']
        os: ['ubuntu-latest']

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code 
        uses: actions/checkout@v2

      - name: use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, test
        run: |
          npm install
          npm run build --if-present
          npm run test

      # - name: Archive build output
      #   uses: actions/upload-artifact@v1
      #   with: 
      #     name: app
      #     path: .
      
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    environment:
      name: nicktrog.dev

    steps:
      # - name: Retrieve build output from previous job
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: app
      #     path: .
      
      - name: deploy
        run: echo Completed deployment
